name: pythia
channels:
- conda-forge
- nodefaults
dependencies:
- matplotlib
- pandas
- pre-commit
- pyyaml
- mystmd
- jupyterlab
- cartopy
- numpy
- matplotlib
- google-api-python-client
- pip
- pip:
    - google-analytics-data
