name: trigger-site-build
on:
  pull_request:

jobs:
  build:
    uses: ProjectPythia/cookbook-actions/.github/workflows/build-book.yaml@main
    with:
      artifact_name: book-zip-${{ github.event.number }}
      base_url: '/_preview/${{ github.event.number }}'
      path_to_notebooks: 'portal'
      # Other input options are possible, see ProjectPythia/cookbook-actions/.github/workflows/build-book.yaml
